<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Entities\Module'                        => __DIR__ . '/Module.php',
    'Entities\Controller\DefaultController' => __DIR__ . '/src/Entities/Controller/DefaultController.php',
    'EntitiesTest\Framework\TestCase'        => __DIR__ . '/tests/Entities/Framework/TestCase.php',
    'EntitiesTest\SampleTest'                => __DIR__ . '/tests/Entities/SampleTest.php',
);
