<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Frontend\Module'                        => __DIR__ . '/Module.php',
    'Frontend\Controller\IndexController' => __DIR__ . '/src/Frontend/Controller/IndexController.php',
    'FrontendTest\Framework\TestCase'        => __DIR__ . '/tests/Frontend/Framework/TestCase.php',
    'FrontendTest\SampleTest'                => __DIR__ . '/tests/Frontend/SampleTest.php',
);
