<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'MediaFiles\Module'                        => __DIR__ . '/Module.php',
    'MediaFiles\Controller\IndexController' => __DIR__ . '/src/MediaFiles/Controller/IndexController.php',
    'MediaFilesTest\Framework\TestCase'        => __DIR__ . '/tests/MediaFiles/Framework/TestCase.php',
    'MediaFilesTest\SampleTest'                => __DIR__ . '/tests/MediaFiles/SampleTest.php',
);
