<?php
echo $this->form()->openTag($form);
echo $this->formLabel($form->get('name'));
echo $this->formElement($form->get('name'));
echo $this->formElementErrors($form->get('name'));
echo $this->formLabel($form->get('content'));
echo $this->formElement($form->get('content'));
echo $this->formElementErrors($form->get('content'));
echo $this->formLabel($form->get('customfield1'));
echo $this->formElement($form->get('customfield1'));
echo $this->formElementErrors($form->get('customfield1'));

echo $this->formLabel($form->get('customfield2'));
echo $this->formElement($form->get('customfield2'));
echo $this->formElementErrors($form->get('customfield2'));
echo $this->formElement($form->get('edit_id'));
echo $this->formElement($form->get('submit'));
echo $this->form()->closeTag($form);
?>

<div id="editformresult" class="editformresult"></div>