<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Login\Module'                        => __DIR__ . '/Module.php',
    'Login\Controller\SkeletonController' => __DIR__ . '/src/Login/Controller/SkeletonController.php',
    'LoginTest\Framework\TestCase'        => __DIR__ . '/tests/Login/Framework/TestCase.php',
    'LoginTest\SampleTest'                => __DIR__ . '/tests/Login/SampleTest.php',
);
