<?php 
echo $this->form()->openTag($form);
echo $this->formLabel($form->get('caption'));
echo $this->formElement($form->get('caption'));
echo $this->formElementErrors($form->get('caption'));
echo $this->formLabel($form->get('description'));
echo $this->formElement($form->get('description'));
echo $this->formElementErrors($form->get('description'));
echo $this->formLabel($form->get('customfield1'));
echo $this->formElement($form->get('customfield1'));
echo $this->formElementErrors($form->get('customfield1'));

echo $this->formLabel($form->get('customfield2'));
echo $this->formElement($form->get('customfield2'));
echo $this->formElementErrors($form->get('customfield2'));
echo $this->formElement($form->get('edit_id'));
echo $this->formElement($form->get('submit'));
echo $this->form()->closeTag($form);
?>

<div id="editformresult" class="editformresult"></div>