<h1>Home</h1>
<?php 
$this->flashmessenger()->setMessageSeparatorString('<br />');
$this->flashmessenger()->setMessageOpenFormat('<div class="alert alert-info">');
$this->flashmessenger()->setMessageCloseString('</div>');

$flash = $this->flashMessenger();
$flash->setMessageOpenFormat('<div%s>
     <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
         &times;
     </button>
     <ul><li>')
     ->setMessageSeparatorString('</li><li>')
     ->setMessageCloseString('</li></ul></div>');

echo $this->flashmessenger()->render("logout",array('alert', 'alert-dismissable', 'alert-success'));
?>

